(define ((
  (hertz-of (lambda (pair fundamental)
    (quotient (times fundamental (car pair))
              (cdr pair))))
  (sing (lambda (voice fundamental)
    (print (list (quote voice)
                 (car voice)
                 (cadr voice)
                 (hertz-of (cadr voice) fundamental)))))
  (hit (lambda (voices fundamental)
    (cond ((null voices) (quote amen))
          (t (cons (sing (car voices) fundamental)
                   (hit  (cdr voices) fundamental))))))
  (vamp (lambda (voices fundamental n)
    (cond ((zerop n) (quote fin))
          (t (cons (hit voices fundamental)
                   (vamp voices fundamental (sub1 n)))))))
)))
(vamp
  (quote ((b    (1  . 1)  (0  0 0))
          (dis  (5  . 4)  (-2 0 1))
          (fis  (3  . 2)  (-1 1 0))
          (ais  (15 . 8)  (-3 1 1))))
  246.942
  8)
